### ISSUE TITLE
是否支持1.19.3

### ISSUE THREAD

**Issue by QianFuv** [mcdoeswhat/AmazingBot-4#1]
看到-->   https://www.mcsky.net/thread-72-1-1.html   并未注明适用于1.19.3  所以来问问

**Comment by mcdoeswhat** [comment]
只要Bukkit api没变,mc出2.0都支持
机器人本身只用了bukkit的api,和mc里面的物品生物没有任何关系

**Comment by QianFuv** [comment]
> 只要Bukkit api没变,mc出2.0都支持
> 机器人本身只用了bukkit的api,和mc里面的物品生物没有任何关系

噢噢谢谢 顺便问一下那些附属插件也是一样的情况吗

**Comment by mcdoeswhat** [comment]
和物品有关的有可能不行，比如查看背包的，还没更新

**Comment by QianFuv** [comment]
> 和物品有关的有可能不行，比如查看背包的，还没更新

噢噢这样  最后请问一下所有插件1.18.2版本都是全功能的吧

**Comment by mcdoeswhat** [comment]
应该是

**Comment by QianFuv** [comment]
> 应该是

好的谢谢啦 如果您有时间期待更新喔
