### ISSUE TITLE
指令结果返回有误

### ISSUE THREAD

**Issue by QianFuv** [mcdoeswhat/AmazingBot-4#2]
![IMG_20230130_195419.jpg](https://user-images.githubusercontent.com/111696321/215470161-c555bb77-b98f-4396-9e7e-c8b483d1b189.jpg)
![Screenshot_2023-01-30-19-53-23-64_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/111696321/215470182-fef1e2b8-00ac-464f-81e7-01a853b30530.jpg)

需完善

purper 1.18.2 1632

**Comment by mcdoeswhat** [comment]
看cqhttp后台

**Comment by mcdoeswhat** [comment]
哦对这个是服务器本身命令,不支持返回的,只能返回插件命令,例如ess

**Comment by QianFuv** [comment]
> 哦对这个是服务器本身命令,不支持返回的,只能返回插件命令,例如ess

但是第一个是spark插件的执行结果  我再试试其他插件

**Comment by mcdoeswhat** [comment]
第一个是直接给服务器后台返回的，不是给发送者返回的，如果返回不了是什么都不会显示的

**Comment by mcdoeswhat** [comment]
插件是模拟发送者执行指令，然后拦截发送者的消息合并后发送到Q群

**Comment by mcdoeswhat** [comment]
spark估计判断了发送者是服务器后台后，直接发送到后台了

**Comment by QianFuv** [comment]
原来是这样  其他命令确实可以返回  谢谢了
