### ISSUE TITLE
显示回复消息、表情和动画表情（这两个显示文字描述就好）、群公告（摘要前几句或者几个词？）、卡片消息（类似网易云音乐分享卡片）

### ISSUE THREAD

**Issue by QianFuv** [mcdoeswhat/AmazingBot-4#3]
现在回复消息是这样的
![image](https://user-images.githubusercontent.com/111696321/215474997-0cc5adf4-4580-4e43-a961-80acbe05d3b4.png)

回复消息能否显示为类似下面这样的
![image](https://user-images.githubusercontent.com/111696321/215475103-4b9b2286-6b01-4d3b-98e6-989a15b7a4af.png)

表情和动画表情类似显示为[doge]、[动画表情]

群公告类似：[群公告]：114514......

卡片消息类似：[网易云音乐]：love story - ..........

**Comment by mcdoeswhat** [comment]
附属聊天只是花几个小时随便写的，如果要的话得找人另外开发

**Comment by mcdoeswhat** [comment]
消息发多了腾讯百分百会封号的，除非你打算开只有几个人的服

**Comment by QianFuv** [comment]
但是像回复消息显示这样的真的是刚需啊qwq

**Comment by QianFuv** [comment]
要不大佬再完善一下？我接受有偿

**Comment by mcdoeswhat** [comment]
没空

**Comment by QianFuv** [comment]
好吧 那我只能放弃这个机器人了
