### ISSUE TITLE
能不能支持反向ws连接

### ISSUE THREAD

**Issue by leiji001** [mcdoeswhat/AmazingBot-4#5]

**Comment by mcdoeswhat** [comment]
为什么有这个需求

**Comment by leiji001** [comment]
部署的机器人并不在公网环境，服务端无法通过正向ws连接到机器人

**Comment by mcdoeswhat** [comment]
> 部署的机器人并不在公网环境，服务端无法通过正向ws连接到机器人

为啥不直接在服务端部署

**Comment by leiji001** [comment]
风控原因把机器人部署在家宽环境

**Comment by mcdoeswhat** [comment]
> 风控原因把机器人部署在家宽环境

你可以复制整个机器人文件夹到服务端的，只要本地登录成功，然后复制包括device.json和session.token的这两个文件
机器人的设备信息和登录token就能保存，服务端就不会风控了

**Comment by leiji001** [comment]
感谢指导，不过还是希望后续能够支持该项功能
