### ISSUE TITLE
ABCustomMessage的代码仓库上传申请

### ISSUE THREAD

**Issue by haishen668** [mcdoeswhat/AmazingBot-4#6]
在使用ABCustomMessage的时候我遇到了一些问题，使用Graphics2D中默认的字体库无法满足我的需求，我想使用拓展的字体。我对您的代码进行了修改，想把这个修改提交给你，我希望作者如果可以的话能够创建该仓库，
添加功能如下:
1.可以使用自定义ttf字体文件作为Graphics2D渲染时的font对象（自定义字体）
2.解析颜色代码例如&a，&b，也可以解析十六进制的颜色代码
3.可以进行字符串拼接且颜色自定义text: "&#F2994A%vault_eco_balance%&#7F8A9B枚"
效果图如下:
![42e7da7cae2c7c0308c83af974cb4612](https://github.com/mcdoeswhat/AmazingBot-4/assets/88919253/8c752047-cb5d-40b9-9449-f35021d687c5)
![6dc7e00b8d72f356c04d474eab249092](https://github.com/mcdoeswhat/AmazingBot-4/assets/88919253/2689a70e-bfe8-45b8-8fb4-0f549b0a54a3)
![fe2d976f12aa0c07c77e3a469e0412a9](https://github.com/mcdoeswhat/AmazingBot-4/assets/88919253/55bd55a1-4817-43d7-950e-be11c9ba5a85)

**Comment by mcdoeswhat** [comment]
你fork下或者建个pullrequest就行了

**Comment by haishen668** [comment]
这个fork的不是amazingbot的仓库吗

**Comment by mcdoeswhat** [comment]
忘了，abcm我没开源，那没办法了

**Comment by haishen668** [comment]
我就是想问这个，abcm能开源吗

**Comment by mcdoeswhat** [comment]
没混淆的，你反编译发就行

**Comment by haishen668** [comment]
好的
